# Generated by Django 5.0.6 on 2026-05-13 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0002_initial"),
        ("homework", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homework_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homeworkassignment",
            name="class_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework",
                to="classes.classsession",
            ),
        ),
        migrations.AddField(
            model_name="homeworkchecklistitem",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_items",
                to="homework.homeworkassignment",
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="homework.homeworkassignment",
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homework_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmissionitem",
            name="checklist_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="homework.homeworkchecklistitem",
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmissionitem",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="homework.homeworksubmission",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="homeworksubmission",
            unique_together={("assignment", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="homeworksubmissionitem",
            unique_together={("submission", "checklist_item")},
        ),
    ]
