# Generated by Django 5.0.6 on 2026-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("all", "All Students"),
                    ("trial", "Trial Students"),
                    ("active_enrolment", "Currently Enrolled"),
                    ("lapsed", "Lapsed Students"),
                ],
                default="all",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Send"),
                    ("after_first_class", "After First Class"),
                    ("after_season_ends", "After Season Ends"),
                    ("scheduled", "Scheduled Date"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
    ]
