# Generated by Django 5.0.6 on 2026-05-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_add_audience_trigger_to_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Free Text"),
                    ("rating", "Star Rating"),
                    ("multiple_choice", "Multiple Choice"),
                    ("checkbox", "Checkboxes"),
                    ("yes_no", "Yes / No"),
                    ("scale", "Scale (1–10)"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
