# Generated by Django 5.0.6 on 2026-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("no_show", "No-show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="present",
                        max_length=15,
                    ),
                ),
                ("no_show_fee_charged", models.BooleanField(default=False)),
                ("no_show_fee_waived", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-occurrence__date"],
            },
        ),
    ]
