# Generated by Django 5.2.14 on 2026-05-15 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_makeup_credit"),
        ("classes", "0011_occurrence_cover_needed"),
    ]

    operations = [
        migrations.AddField(
            model_name="makeupcredit",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="makeup_credits",
                to="classes.season",
            ),
        ),
    ]
