# Generated by Django 5.0.6 on 2026-05-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_add_class_pass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("present", "Present"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                    ("no_show", "No-show"),
                    ("cancelled", "Cancelled"),
                ],
                default="present",
                max_length=15,
            ),
        ),
    ]
