[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py seed && python manage.py set_test_passwords && gunicorn config.wsgi --log-file -"
restartPolicyType = "on_failure"
