[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py clean_studio_features && python manage.py migrate && python manage.py seed_demo && python manage.py set_test_passwords && gunicorn config.wsgi --bind 0.0.0.0:${PORT:-8000} --log-file -"
restartPolicyType = "on_failure"
