# Generated by Django 5.0.6 on 2026-05-15 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="communitygroup",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="community_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
