# Generated by Django 5.2.14 on 2026-05-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_communitygroup_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppost",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
