# Generated by Django 5.0.6 on 2026-05-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "studio_name",
                    models.CharField(default="Duality Pole Studio", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        default="hello@dualitypole.com.au", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("instagram", models.CharField(blank=True, max_length=100)),
                (
                    "timezone",
                    models.CharField(default="Australia/Sydney", max_length=50),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("primary_colour", models.CharField(default="#CCFF00", max_length=20)),
                ("enquiries_email", models.EmailField(blank=True, max_length=254)),
                ("urgent_email", models.EmailField(blank=True, max_length=254)),
                ("cancellation_window_hours", models.PositiveIntegerField(default=24)),
                (
                    "no_show_fee",
                    models.DecimalField(decimal_places=2, default=20, max_digits=6),
                ),
                (
                    "late_cancel_fee",
                    models.DecimalField(decimal_places=2, default=10, max_digits=6),
                ),
                ("credit_expiry_days", models.PositiveIntegerField(default=60)),
                ("max_freeze_weeks", models.PositiveIntegerField(default=8)),
                ("gst_registered", models.BooleanField(default=True)),
                ("abn", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "verbose_name": "Studio Settings",
            },
        ),
    ]
