# Generated by Django 5.0.6 on 2026-05-14 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_order_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (9am–12pm)"),
                            ("afternoon", "Afternoon (12pm–5pm)"),
                            ("evening", "Evening (5pm–10pm)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "slot"],
                "unique_together": {("instructor", "day_of_week", "slot")},
            },
        ),
        migrations.CreateModel(
            name="StudentForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("parq", "PAR-Q Health Questionnaire"),
                            ("waiver", "Liability Waiver"),
                            ("survey", "Survey"),
                        ],
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("responses", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["completed", "form_type"],
                "unique_together": {("student", "form_type")},
            },
        ),
    ]
