# Generated by Django 5.0.6 on 2026-05-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_instructor_pay_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiosettings",
            name="kisi_api_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="kisi_org_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
