# Generated by Django 5.0.6 on 2026-05-14 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_set_pricing_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=50)),
                ("self_assessed", models.BooleanField(default=False)),
                ("teacher_confirmed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["level", "skill_name"],
                "unique_together": {("student", "skill_name")},
            },
        ),
    ]
