# Generated by Django 5.0.6 on 2026-05-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_emaillist_emailcampaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="actions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="conditions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="trigger_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
