# Generated by Django 5.0.6 on 2026-05-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_automationrule_actions_automationrule_conditions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiosettings",
            name="instagram_access_token",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="instagram_page_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="instagram_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="meta_app_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
