# Generated by Django 5.0.6 on 2026-05-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="perm_approve_plans",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="perm_billing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="perm_bulk_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="perm_edit_profiles",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="perm_reports",
            field=models.BooleanField(default=False),
        ),
    ]
