# Generated by Django 5.0.6 on 2026-05-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_automation_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiosettings",
            name="season_pricing_config",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
