# Generated by Django 5.0.6 on 2026-05-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_season_pricing_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("announcement", "Student Announcement"),
                    ("staff", "Staff Note"),
                ],
                default="announcement",
                max_length=20,
            ),
        ),
    ]
