# Generated by Django 5.2.14 on 2026-05-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_instructor_unavailable_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiosettings",
            name="form_health_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="form_photo_consent_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="form_season_agreement_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="form_waiver_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
