# Generated by Django 5.0.6 on 2026-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_mediaitem_available_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="roster_name",
            field=models.CharField(
                choices=[("first_name", "First name"), ("nickname", "Nickname")],
                default="first_name",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_in_roster",
            field=models.BooleanField(default=False),
        ),
    ]
