# Generated by Django 5.0.6 on 2026-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_roster_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("reminder", "Reminder"),
                    ("waitlist", "Waitlist"),
                    ("payment", "Payment"),
                    ("form", "Form"),
                    ("info", "Info"),
                    ("message", "Message"),
                    ("cancellation", "Cancellation"),
                    ("warning", "Warning"),
                    ("success", "Success"),
                    ("billing", "Billing"),
                ],
                default="info",
                max_length=20,
            ),
        ),
    ]
