# Generated by Django 5.0.6 on 2026-05-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_alter_challenge_target_value_devicepushtoken"),
        ("users", "0037_add_product_image"),
    ]

    operations = []
