# Generated by Django 5.0.6 on 2026-05-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_merge_20260517_1643"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffnote",
            options={"ordering": ["archived", "-created_at"]},
        ),
        migrations.AddField(
            model_name="staffnote",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffnote",
            name="is_permanent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffnote",
            name="recheck_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
