# Generated by Django 5.0.6 on 2026-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_add_class_pass_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="booking_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
