# Generated by Django 5.0.6 on 2026-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_add_price_class_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="booking_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Admin can set this to prevent the student from making new bookings.",
            ),
        ),
    ]
