# Generated by Django 5.0.6 on 2026-05-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_add_price_casual_enrolled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studiosettings",
            name="price_class_pass",
            field=models.DecimalField(decimal_places=2, default=120, max_digits=8),
        ),
    ]
