# Generated by Django 5.0.6 on 2026-05-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_alter_studiosettings_price_class_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
