# Generated by Django 5.0.6 on 2026-05-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0046_studiosettings_studio_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiosettings",
            name="address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="trial_intro_body",
            field=models.TextField(
                blank=True,
                default="Your first class, no experience needed. Wear comfortable activewear, bring water — we'll do the rest.",
            ),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="trial_intro_headline",
            field=models.CharField(
                blank=True, default="Try Your First Class", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
