# Generated by Django 5.0.6 on 2026-05-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0047_add_address_website_trial_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiosettings",
            name="form_health_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="form_photo_consent_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="form_season_agreement_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="form_waiver_required",
            field=models.BooleanField(default=True),
        ),
    ]
