# Generated by Django 5.0.6 on 2026-05-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_add_form_required_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiosettings",
            name="season_discount_tiers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="studiosettings",
            name="cancellation_window_hours",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
