# Generated by Django 5.0.6 on 2026-05-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0049_add_season_discount_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Public bio shown on the Team page"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="instructor_instagram",
            field=models.CharField(
                blank=True, help_text="Instagram handle (without @)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="instructor_tagline",
            field=models.CharField(
                blank=True,
                help_text="Short subtitle shown under the name on the Team page",
                max_length=200,
            ),
        ),
    ]
