# Generated by Django 5.0.6 on 2026-05-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0028_merge_20260525_1254"),
        ("users", "0053_studiosettings_kisi_place_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="block_reason",
            field=models.TextField(
                blank=True, help_text="Reason for booking block (admin notes)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cleared_to_teach",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sessions this instructor is cleared to teach (admin-assigned)",
                related_name="cleared_instructors",
                to="classes.classsession",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_shadow_instructor",
            field=models.BooleanField(
                default=False,
                help_text="Shadow instructors earn $30/class instead of $40",
            ),
        ),
    ]
