# Generated by Django 5.0.6 on 2026-05-25 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0029_locker_status_pending_return"),
        ("users", "0059_studentskill_instructor_status_is_focus"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all", "All students"),
                    ("specific", "Specific students"),
                    ("enrolled_season", "Enrolled in season"),
                    ("level", "Students at level(s)"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="audience_levels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="announcement",
            name="audience_season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="classes.season",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="audience_students",
            field=models.ManyToManyField(
                blank=True,
                related_name="targeted_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="cta_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="announcement",
            name="cta_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="announcement",
            name="modal_dismissed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="dismissed_modal_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="show_as_modal",
            field=models.BooleanField(default=False),
        ),
    ]
