# Generated by Django 5.0.6 on 2026-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0029_locker_status_pending_return"),
        ("users", "0060_announcement_modal_broadcast"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_sessions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific sessions this student cannot book (admin-set)",
                related_name="level_blocked_students",
                to="classes.classsession",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="max_booking_level",
            field=models.CharField(
                blank=True,
                help_text="Hard cap — student cannot book above this level (admin-set, stays until removed)",
                max_length=50,
            ),
        ),
    ]
