# Generated by Django 5.0.6 on 2026-05-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0061_user_max_booking_level_blocked_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentskill",
            name="instructor_notes",
            field=models.TextField(blank=True),
        ),
    ]
