# Generated by Django 5.0.6 on 2026-05-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0062_add_skill_instructor_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="extra_ctas",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Additional CTA buttons: [{label, url}]",
            ),
        ),
    ]
