# Generated by Django 5.0.6 on 2026-05-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0063_announcement_extra_ctas"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_check_required",
            field=models.BooleanField(
                default=False,
                help_text="Flag for admin to verify this student is 18+. Auto-set when DOB is within 1 year of 18th birthday at registration.",
            ),
        ),
    ]
