# Generated by Django 5.0.6 on 2026-05-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0039_classsession_start_end_week"),
        ("users", "0064_user_id_check_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorpayrecord",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instructorpayrecord",
            name="occurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pay_records",
                to="classes.classoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="instructorpayrecord",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="instructorpayrecord",
            name="student_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studiosettings",
            name="waiver_text",
            field=models.TextField(blank=True),
        ),
    ]
