# Generated by Django 5.0.6 on 2026-05-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0065_instructorpayrecord_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="rule_params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tag",
            name="rule_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("enrolled_in_class", "Enrolled in class"),
                    ("first_timer", "First timer this season"),
                    ("active_enrolment", "Has active enrolment this season"),
                    ("three_plus_classes", "3+ classes this season"),
                    ("lapsed_1", "Lapsed — missed 1 season"),
                    ("lapsed_2", "Lapsed — missed 2 seasons"),
                    ("lapsed_3_plus", "Lapsed — missed 3+ seasons"),
                    ("casual_only", "Casual bookings only this season"),
                    ("trial_not_converted", "Trial, never converted"),
                    ("has_locker", "Has active locker"),
                    ("level", "Level"),
                ],
                max_length=50,
            ),
        ),
    ]
