# Generated by Django 5.0.6 on 2026-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0066_tag_rule_params_tag_rule_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentskill",
            name="self_rating",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("almost", "Almost"), ("no", "No")],
                max_length=10,
            ),
        ),
    ]
