# Generated by Django 5.0.6 on 2026-05-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0067_add_self_rating_to_studentskill"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="timing",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
