from django.urls import path
from . import views
from . import instagram as instagram_views

urlpatterns = [
    path('me/', views.MeView.as_view(), name='user-me'),
    path('import/', views.BulkImportView.as_view(), name='user-bulk-import'),
    path('settings/', views.StudioSettingsView.as_view(), name='studio-settings'),
    path('announcements/', views.AnnouncementListView.as_view(), name='announcement-list'),
    path('announcements/<int:pk>/', views.AnnouncementDetailView.as_view(), name='announcement-detail'),
    path('announcements/<int:pk>/acknowledge/', views.AnnouncementAcknowledgeView.as_view(), name='announcement-acknowledge'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('automations/stats/', views.AutomationStatsView.as_view(), name='automation-stats'),
    path('automation-runs/', views.AutomationRunListView.as_view(), name='automation-run-list'),
    path('automations/', views.AutomationRuleView.as_view(), name='automation-rules'),
    path('automations/<int:pk>/', views.AutomationRuleDetailView.as_view(), name='automation-rule-detail'),
    path('orders/', views.OrderListView.as_view(), name='order-list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('push-token/', views.push_token, name='push-token'),
    path('notifications/', views.NotificationListView.as_view(), name='notification-list'),
    path('notifications/bulk/', views.BulkNotificationView.as_view(), name='notification-bulk'),
    path('notifications/mark-read/', views.NotificationMarkReadView.as_view(), name='notification-mark-read'),
    path('notifications/<int:pk>/escalate/', views.EscalateNotificationView.as_view(), name='notification-escalate'),
    path('availability/', views.InstructorAvailabilityView.as_view(), name='instructor-availability'),
    path('unavailable-dates/', views.InstructorUnavailableDateView.as_view(), name='instructor-unavailable-dates'),
    path('unavailable-dates/<int:pk>/', views.InstructorUnavailableDateDetailView.as_view(), name='instructor-unavailable-date-detail'),
    path('forms/pending-required/', views.StudentFormPendingRequiredView.as_view(), name='forms-pending-required'),
    path('forms/', views.StudentFormView.as_view(), name='student-forms'),
    path('pay-records/', views.InstructorPayRecordListView.as_view(), name='instructor-pay-records'),
    path('pay-records/<int:pk>/', views.InstructorPayRecordDetailView.as_view(), name='instructor-pay-record-detail'),
    path('square-sync/', views.SquareSyncView.as_view(), name='square-sync'),
    path('<int:user_pk>/skills/', views.StudentSkillView.as_view(), name='student-skills'),
    path('<int:user_pk>/calculate-pay/', views.CalculatePayView.as_view(), name='calculate-pay'),
    path('pending-skills/', views.PendingSkillsView.as_view(), name='pending-skills'),
    path('tags/', views.TagListView.as_view()),
    path('tags/<int:pk>/', views.TagDetailView.as_view()),
    path('<int:user_pk>/tags/', views.StudentTagView.as_view()),
    path('skill-levels/', views.SkillLevelListView.as_view()),
    path('skill-levels/<int:pk>/', views.SkillLevelDetailView.as_view()),
    path('skill-groups/', views.SkillGroupListView.as_view()),
    path('skill-groups/<int:pk>/', views.SkillGroupDetailView.as_view()),
    path('skill-definitions/', views.SkillDefinitionListView.as_view()),
    path('skill-definitions/<int:pk>/', views.SkillDefinitionDetailView.as_view()),
    path('media/', views.MediaItemListView.as_view()),
    path('media/<int:pk>/', views.MediaItemDetailView.as_view()),
    path('campaigns/', views.EmailCampaignListView.as_view()),
    path('campaigns/<int:pk>/', views.EmailCampaignDetailView.as_view()),
    path('campaigns/<int:pk>/send/', views.EmailCampaignSendView.as_view(), name='campaign-send'),
    path('email-lists/', views.EmailListListView.as_view()),
    path('email-lists/<int:pk>/', views.EmailListDetailView.as_view()),
    path('email-lists/<int:pk>/export/', views.EmailListExportView.as_view()),
    path('instagram/webhook/', instagram_views.InstagramWebhookView.as_view()),
    path('instagram/auth/', instagram_views.InstagramAuthView.as_view()),
    path('instagram/callback/', instagram_views.InstagramCallbackView.as_view()),
    path('referrals/', views.ReferralListView.as_view()),
    path('action-items/', views.ActionItemListView.as_view()),
    path('action-items/<int:pk>/', views.ActionItemDetailView.as_view()),
    path('challenges/', views.ChallengeListView.as_view()),
    path('challenges/<int:pk>/', views.ChallengeDetailView.as_view()),
    path('challenges/<int:pk>/leaderboard/', views.ChallengeLeaderboardView.as_view()),
    path('challenges/<int:pk>/opt-in/', views.ChallengeOptInView.as_view()),
    path('challenges/<int:pk>/recalculate/', views.ChallengeBulkProgressView.as_view()),
    path('mailchimp/status/', views.MailchimpStatusView.as_view()),
    path('mailchimp/sync/', views.MailchimpSyncView.as_view()),
    path('xero/connect/', views.XeroConnectView.as_view()),
    path('xero/callback/', views.XeroCallbackView.as_view()),
    path('xero/status/', views.XeroStatusView.as_view()),
    path('xero/sync/', views.XeroSyncView.as_view()),
    path('assistant/', views.AssistantView.as_view()),
    path('change-password/', views.ChangePasswordView.as_view()),
    path('', views.UserListView.as_view(), name='user-list'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user-detail'),
    path('<int:user_pk>/notes/', views.StaffNoteListView.as_view(), name='staff-notes'),
    path('<int:user_pk>/notes/<int:pk>/', views.StaffNoteDetailView.as_view(), name='staff-note-detail'),
    path('notes/recheck-today/', views.RecheckNotesTodayView.as_view(), name='notes-recheck-today'),
    path('<int:pk>/set-password/', views.AdminSetPasswordView.as_view(), name='user-set-password'),
]

leads_urlpatterns = [
    path('', views.LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead-detail'),
]
