from django.urls import path
from . import views
from . import instagram as instagram_views

urlpatterns = [
    path('me/', views.MeView.as_view(), name='user-me'),
    path('import/', views.BulkImportView.as_view(), name='user-bulk-import'),
    path('settings/', views.StudioSettingsView.as_view(), name='studio-settings'),
    path('announcements/', views.AnnouncementListView.as_view(), name='announcement-list'),
    path('announcements/<int:pk>/', views.AnnouncementDetailView.as_view(), name='announcement-detail'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('automations/stats/', views.AutomationStatsView.as_view(), name='automation-stats'),
    path('automation-runs/', views.AutomationRunListView.as_view(), name='automation-run-list'),
    path('automations/', views.AutomationRuleView.as_view(), name='automation-rules'),
    path('automations/<int:pk>/', views.AutomationRuleDetailView.as_view(), name='automation-rule-detail'),
    path('orders/', views.OrderListView.as_view(), name='order-list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('notifications/', views.NotificationListView.as_view(), name='notification-list'),
    path('notifications/mark-read/', views.NotificationMarkReadView.as_view(), name='notification-mark-read'),
    path('availability/', views.InstructorAvailabilityView.as_view(), name='instructor-availability'),
    path('forms/', views.StudentFormView.as_view(), name='student-forms'),
    path('pay-records/', views.InstructorPayRecordListView.as_view(), name='instructor-pay-records'),
    path('pay-records/<int:pk>/', views.InstructorPayRecordDetailView.as_view(), name='instructor-pay-record-detail'),
    path('square-sync/', views.SquareSyncView.as_view(), name='square-sync'),
    path('<int:user_pk>/skills/', views.StudentSkillView.as_view(), name='student-skills'),
    path('tags/', views.TagListView.as_view()),
    path('tags/<int:pk>/', views.TagDetailView.as_view()),
    path('<int:user_pk>/tags/', views.StudentTagView.as_view()),
    path('skill-levels/', views.SkillLevelListView.as_view()),
    path('skill-levels/<int:pk>/', views.SkillLevelDetailView.as_view()),
    path('skill-groups/', views.SkillGroupListView.as_view()),
    path('skill-groups/<int:pk>/', views.SkillGroupDetailView.as_view()),
    path('skill-definitions/', views.SkillDefinitionListView.as_view()),
    path('skill-definitions/<int:pk>/', views.SkillDefinitionDetailView.as_view()),
    path('media/', views.MediaItemListView.as_view()),
    path('media/<int:pk>/', views.MediaItemDetailView.as_view()),
    path('campaigns/', views.EmailCampaignListView.as_view()),
    path('campaigns/<int:pk>/', views.EmailCampaignDetailView.as_view()),
    path('email-lists/', views.EmailListListView.as_view()),
    path('email-lists/<int:pk>/', views.EmailListDetailView.as_view()),
    path('email-lists/<int:pk>/export/', views.EmailListExportView.as_view()),
    path('instagram/webhook/', instagram_views.InstagramWebhookView.as_view()),
    path('instagram/auth/', instagram_views.InstagramAuthView.as_view()),
    path('instagram/callback/', instagram_views.InstagramCallbackView.as_view()),
    path('referrals/', views.ReferralListView.as_view()),
    path('assistant/', views.AssistantView.as_view()),
    path('change-password/', views.ChangePasswordView.as_view()),
    path('', views.UserListView.as_view(), name='user-list'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user-detail'),
    path('<int:user_pk>/notes/', views.StaffNoteListView.as_view(), name='staff-notes'),
]

leads_urlpatterns = [
    path('', views.LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead-detail'),
]
