from django.urls import path
from . import views

urlpatterns = [
    path('studios/', views.StudioListView.as_view(), name='studio-list'),
    path('studios/<int:pk>/', views.StudioDetailView.as_view(), name='studio-detail'),
    path('categories/', views.ClassCategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', views.ClassCategoryDetailView.as_view(), name='category-detail'),
    path('sessions/', views.ClassSessionListView.as_view(), name='session-list'),
    path('sessions/<int:pk>/', views.ClassSessionDetailView.as_view(), name='session-detail'),
    path('occurrences/', views.ClassOccurrenceListView.as_view(), name='occurrence-list'),
    path('occurrences/<int:pk>/', views.ClassOccurrenceDetailView.as_view(), name='occurrence-detail'),
    path('seasons/', views.SeasonListView.as_view(), name='season-list'),
    path('seasons/<int:pk>/', views.SeasonDetailView.as_view(), name='season-detail'),
    path('lockers/', views.LockerListView.as_view(), name='locker-list'),
    path('lockers/eligible/', views.LockerEligibleStudentsView.as_view(), name='locker-eligible'),
    path('lockers/<int:pk>/', views.LockerDetailView.as_view(), name='locker-detail'),
    path('lockers/<int:pk>/lost_key/', views.LockerLostKeyView.as_view(), name='locker-lost-key'),
    path('kisi/grants/', views.KisiGrantListView.as_view(), name='kisi-grant-list'),
    path('kisi/grants/<int:pk>/', views.KisiGrantDetailView.as_view(), name='kisi-grant-detail'),
    path('sessions/<int:session_pk>/chat/', views.ClassChatView.as_view(), name='class-chat'),
    path('stats/', views.ClassStatsView.as_view(), name='class-stats'),
    path('workshops/', views.WorkshopListView.as_view(), name='workshop-list'),
    path('workshops/<int:pk>/', views.WorkshopDetailView.as_view(), name='workshop-detail'),
    path('workshops/<int:pk>/book/', views.WorkshopBookView.as_view(), name='workshop-book'),
    path('workshops/<int:pk>/bookings/', views.WorkshopBookingListView.as_view(), name='workshop-bookings'),
    path('practice/', views.PracticeSlotListView.as_view(), name='practice-list'),
    path('practice/<int:pk>/', views.PracticeSlotDetailView.as_view(), name='practice-detail'),
    path('practice/<int:pk>/book/', views.PracticeSlotBookView.as_view(), name='practice-book'),
    path('practice/<int:pk>/cancel/', views.PracticeSlotCancelView.as_view(), name='practice-cancel'),
    path('practice/my-bookings/', views.MyPracticeBookingsView.as_view(), name='practice-my-bookings'),
    path('practice/all-bookings/', views.AdminPracticeBookingsView.as_view(), name='practice-all-bookings'),
]
