# Generated by Django 5.0.6 on 2026-05-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("waitlisted", "Waitlisted"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=15,
            ),
        ),
    ]
