# Generated by Django 5.2.14 on 2026-05-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0003_alter_enrolment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("waitlisted", "Waitlisted"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("suspended", "Suspended"),
                    ("exemption_requested", "Exemption Requested"),
                ],
                default="active",
                max_length=22,
            ),
        ),
    ]
