# Generated by Django 5.2.14 on 2026-05-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0004_enrolment_exemption_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="intro_email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="is_first_visit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="waiver_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="enrolment",
            name="enrolment_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("casual", "Casual"),
                    ("trial", "Trial"),
                ],
                default="course",
                max_length=10,
            ),
        ),
    ]
