# Generated by Django 5.0.6 on 2026-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0005_add_trial_type_and_onboarding_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="enrolment_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("casual", "Casual"),
                    ("trial", "Trial"),
                    ("catchup", "Catchup"),
                ],
                default="course",
                max_length=10,
            ),
        ),
    ]
