# Generated by Django 5.0.6 on 2026-05-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0006_waitlist_offer_fields"),
        ("enrolments", "0007_enrolment_flag_dismissed"),
    ]

    operations = []
