# Generated by Django 5.0.6 on 2026-05-18 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0009_enrolment_displacement"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled", models.BooleanField(default=False)),
                (
                    "class_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "instructor_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "facilities_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "structure_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrolment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_feedback",
                        to="enrolments.enrolment",
                    ),
                ),
            ],
        ),
    ]
