# Generated by Django 5.0.6 on 2026-05-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0012_classchangerequest_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="classchangerequest",
            name="admin_initiated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classchangerequest",
            name="cancellation_resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit", "Account Credit"),
                    ("refund", "Refund"),
                    ("no_refund", "No Refund"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="classchangerequest",
            name="request_type",
            field=models.CharField(
                choices=[("transfer", "Transfer"), ("cancel", "Cancel")],
                default="transfer",
                max_length=10,
            ),
        ),
    ]
