# Generated by Django 5.0.6 on 2026-05-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0014_classchangerequest_awaiting_response"),
        ("enrolments", "0015_enrolment_level_override"),
    ]

    operations = []
