# Generated by Django 5.0.6 on 2026-05-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0016_merge_20260525_1254"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="waitlist_skip_auto_promote",
            field=models.BooleanField(default=False),
        ),
    ]
