# Generated by Django 5.0.6 on 2026-05-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0017_add_waitlist_skip_auto_promote"),
    ]

    operations = [
        migrations.AddField(
            model_name="classchangerequest",
            name="spot_held",
            field=models.BooleanField(default=False),
        ),
    ]
