# Generated by Django 5.0.6 on 2026-05-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0018_add_change_request_spot_held"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="student_auto_promote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="waitlist_offer_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
