# Generated by Django 5.0.6 on 2026-05-14 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_kisi_grant_studio_place_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("colour", models.CharField(default="#ccff00", max_length=20)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="studio",
            name="capacity",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studio",
            name="features",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studio",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studio",
            name="poles",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="classsession",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="classes.classcategory",
            ),
        ),
    ]
