# Generated by Django 5.0.6 on 2026-05-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0009_workshop_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="studios/"),
        ),
    ]
