# Generated by Django 5.2.14 on 2026-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0010_studio_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoccurrence",
            name="cover_needed",
            field=models.BooleanField(default=False),
        ),
    ]
