# Generated by Django 5.0.6 on 2026-05-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0018_classupsell"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="catchup_cutoff_weeks",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="No catch-up bookings accepted after this many weeks into the season. Leave blank to allow catch-ups any time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="bookings_open",
            field=models.BooleanField(default=False),
        ),
    ]
