# Generated by Django 5.0.6 on 2026-05-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0019_season_bookings_open_catchup_cutoff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casualbooking",
            name="enrolment_type",
            field=models.CharField(
                choices=[
                    ("casual", "Casual"),
                    ("catchup", "Catchup"),
                    ("classpass", "Class Pass"),
                ],
                default="casual",
                max_length=12,
            ),
        ),
    ]
