# Generated by Django 5.0.6 on 2026-05-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0020_extend_enrolment_type_classpass"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="first_timer_body",
            field=models.TextField(
                blank=True,
                help_text="Detailed info shown to first-time students after they book this class.",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="first_timer_headline",
            field=models.CharField(
                blank=True,
                help_text="Short headline shown to students booking this class for the first time.",
                max_length=200,
            ),
        ),
    ]
