# Generated by Django 5.0.6 on 2026-05-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0027_classsession_skill_level"),
        ("classes", "0027_locker_payment_status_invoiced"),
    ]

    operations = []
