# Generated by Django 5.0.6 on 2026-05-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0029_locker_status_pending_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="classcategory",
            name="upsell_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="classcategory",
            name="upsell_headline",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="classcategory",
            name="upsell_target_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category to suggest when a student books a class in this category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upsell_sources",
                to="classes.classcategory",
            ),
        ),
    ]
