# Generated by Django 5.0.6 on 2026-05-25 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0030_add_category_upsell"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonNotificationInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_interests",
                        to="classes.season",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("season", "email")},
            },
        ),
    ]
