# Generated by Django 5.0.6 on 2026-05-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0032_merge_auto_promote_and_season_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="casualbooking",
            name="waitlist_offer_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
