# Generated by Django 5.0.6 on 2026-05-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0037_classsession_prerequisites"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("colour", models.CharField(blank=True, default="#666", max_length=20)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="classsession",
            name="auto_exempt_same_name",
            field=models.BooleanField(
                default=True,
                help_text="Students enrolled in a same-name session are auto-exempt from catch-up cutoff.",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="catchup_eligible_names",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated class names eligible as catch-up destinations for this class.",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="instructor_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount to credit instructor's account per class attended.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custom price for this class. Overrides standard tier pricing.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="requires_full_payment",
            field=models.BooleanField(
                default=False,
                help_text="If True, student must pay the full season fee upfront (no payment plan).",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="classes.tag"
            ),
        ),
    ]
