# Generated by Django 5.0.6 on 2026-05-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0038_tag_classsession_auto_exempt_same_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="end_week",
            field=models.PositiveSmallIntegerField(
                default=8,
                help_text="Week number (1–8) this class stops running within the season.",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="start_week",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Week number (1–8) this class starts running within the season.",
            ),
        ),
    ]
