# Generated by Django 5.0.6 on 2026-05-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0039_classsession_start_end_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicebooking",
            name="attendance_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("present", "Present"),
                    ("no_show", "No-show (fee)"),
                    ("no_show_waived", "No-show (no fee)"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="practicebooking",
            name="kisi_access_granted",
            field=models.BooleanField(default=False),
        ),
    ]
