# Generated by Django 5.0.6 on 2026-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0040_add_practicebooking_attendance_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="exempt_from_season_discount",
            field=models.BooleanField(
                default=False,
                help_text="If True, this class is not counted in the incremental season discount structure.",
            ),
        ),
    ]
