# Generated by Django 5.0.6 on 2026-05-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0041_add_exempt_from_season_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="instructor_notes",
            field=models.TextField(
                blank=True,
                help_text="Persistent notes for instructors (e.g. class quirks, injuries to watch). Copied when duplicating sessions between seasons.",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="syllabus",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Week-by-week plan. Array of {week, title, content, moves} objects.",
            ),
        ),
    ]
