# Generated by Django 5.0.6 on 2026-05-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0042_add_syllabus_instructor_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="classoccurrence",
            name="instructor_credited",
            field=models.BooleanField(default=False),
        ),
    ]
