# Generated by Django 5.0.6 on 2026-05-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="package",
            name="is_intro",
            field=models.BooleanField(default=False),
        ),
    ]
