# Generated by Django 5.2.14 on 2026-05-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_package_intro_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
