# Generated by Django 5.0.6 on 2026-05-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_studentmembership"),
        ("payments", "0012_payment_cash_promise"),
    ]

    operations = []
