# Generated by Django 5.0.6 on 2026-05-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_merge_20260525_1254"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Credit / Debit Card"),
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("account_credit", "Account Credit"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
