# Generated by Django 5.0.6 on 2026-05-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_payment_method_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
