# Generated by Django 5.0.6 on 2026-05-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_payment_admin_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Card"),
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("prompt_card", "Prompt to Add Card"),
                ],
                default="card",
                max_length=20,
            ),
        ),
    ]
