# Generated by Django 5.0.6 on 2026-05-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "helpdesk",
            "0003_conversation_instagram_sender_id_conversation_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="admin_unread",
            field=models.BooleanField(default=False),
        ),
    ]
